web:
    build: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/conf.conf:/etc/nginx/conf.d/site.conf
        - ./nginx/local.conf:/etc/nginx/conf.d/local.conf
        - ./../:/src
        - ./../key:/root/.ssh
    links:
        - php
    ports:
        - "81:80"
php:
    build: php
    environment:
      - TERM=dumb
    volumes:
      - ./../:/src 
