web:
    build: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/
        - ./../../:/src
    links:
        - php
php:
    build: php
    volumes:
        - ./../src/app/backend:/src
        - ./../script:/script
        - ./:/docker
        - ./php/conf:/etc/php7/apache2/conf.d
        - /var/log/php7:/var/log/php7
        - ./php/fpm-conf/:/usr/local/php7/etc/php-fpm.d/
    links:
        - db
    environment:
      - TERM=dumb
    ports:
      - "9000:9000"


node:
    volumes:
       - ./../:/src
    tty: true
    build: node
    ports:
      - "8080:8080"


db:
  image: mariadb
  restart: always
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=b1otope
    - MYSQL_DATABASE=chakatee
    - MYSQL_USER=ed
    - MYSQL_PASSWORD=b1otope
    - TERM=dumb
  volumes:
    - ./db:/etc/mysql/conf.d
    - ./:/opt
  tty: true

phpmyadmin:
   image: corbinu/docker-phpmyadmin
   restart: always
   ports :
    - "85:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=b1otope
   links:
    - db:mysql
