web:
    build: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./../serveur_api:/src
    links:
        - php
php:
    build: php
    volumes:
        - ./../serveur_api:/src
    links:
        - db
    environment:
      - TERM=dumb
        

node:
    volumes:
       - ./../:/src
    tty: true
    build: node
    ports:
      - "8000:8000"
      - "8003:8003"

db:
  image: mariadb
  restart: always
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=b1otope
    - MYSQL_DATABASE=stpc_emlyon
    - MYSQL_USER=ed 
    - MYSQL_PASSWORD=b1otope
    - TERM=dumb
  volumes:
    - ./db:/etc/mysql/conf.d
    - ./:/opt
  tty: true

phpmyadmin:
   image: corbinu/docker-phpmyadmin
   restart: always
   ports :
    - "85:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=b1otope
   links:
    - db:mysql
